# 3.1. Annotation summary statistics

Walkthrough URL = [https://zzz.bwh.harvard.edu/luna-walkthrough/p3/annots/](https://zzz.bwh.harvard.edu/luna-walkthrough/p3/annots/)

URL index: [Home](https://zzz.bwh.harvard.edu/luna-walkthrough/) | [Data](https://zzz.bwh.harvard.edu/luna-walkthrough/data/) | [S1. File QC](https://zzz.bwh.harvard.edu/luna-walkthrough/p1/) | [S2. Signal QC](https://zzz.bwh.harvard.edu/luna-walkthrough/p2) | [S3. Staging](https://zzz.bwh.harvard.edu/luna-walkthrough/p3) | [S4. Artifacts](https://zzz.bwh.harvard.edu/luna-walkthrough/p4) | [S5. Analysis](https://zzz.bwh.harvard.edu/luna-walkthrough/p5)

Notebook index: [Index](../00_index.ipynb) | [S1. File QC](../p1/00_index.ipynb) | [S2. Signal QC](../p2/00_index.ipynb) | [S3. Staging](../p3/00_index.ipynb) | [S4. Artifacts](../p4/00_index.ipynb) | [S5. Analysis](../p5/00_index.ipynb)

---

In [1]:
import lunapi as lp
proj = lp.proj()
proj.sample_list( '../harm1.lst' )

initiated lunapi v1.2.3 <lunapi.lunapi0.luna object at 0x106837930>

read 20 individuals from ../harm1.lst

## Simple tabulations

Luna's `ANNOTS` command can be used to generate simple statistics (e.g. counts, durations) for the annotations associated with a recording:

In [2]:
# luna harm1.lst -o out.db -s ANNOTS
res = proj.silent_proc( 'ANNOTS' )

In [5]:
# destrat out.db +ANNOTS -r ANNOT INST T > tmp/ann.1
tbl = proj.table( 'ANNOTS' , 'ANNOT_INST_T1_T2' ) 
tbl

,ID,ANNOT,INST,T1,T2,CH,DUR,START,START_ELAPSED_HMS,START_HMS,STOP,STOP_ELAPSED_HMS,STOP_HMS
0,F09,Arousal,.,40500000000.0,44600000000.0,.,4.1,40.5,00:00:40.5,22:00:40.5,44.6,00:00:44.6,22:00:44.6
1,F10,Arousal,.,228200000000.0,232800000000.0,.,4.6,228.2,00:03:48.2,22:03:48.2,232.8,00:03:52.8,22:03:52.8
2,F10,Arousal,.,262000000000.0,265100000000.0,.,3.1,262.0,00:04:22,22:04:22,265.1,00:04:25.1,22:04:25.1
3,M01,Arousal,.,285000000000.0,290400000000.0,.,5.4,285.0,00:04:45,22:04:45,290.4,00:04:50.4,22:04:50.4
4,F10,Arousal,.,298700000000.0,307700000000.0,.,9.0,298.7,00:04:58.7,22:04:58.7,307.7,00:05:07.7,22:05:07.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16670,M07,W,W,29340000000000.0,29370000000000.0,.,30.0,29340.0,08:09:00,06:09:00,29370.0,08:09:30,06:09:30
16671,M07,W,W,29370000000000.0,29400000000000.0,.,30.0,29370.0,08:09:30,06:09:30,29400.0,08:10:00,06:10:00
16672,M07,W,W,29400000000000.0,29430000000000.0,.,30.0,29400.0,08:10:00,06:10:00,29430.0,08:10:30,06:10:30
16673,M07,W,W,29580000000000.0,29610000000000.0,.,30.0,29580.0,08:13:00,06:13:00,29610.0,08:13:30,06:13:30
16674,M07,W,W,29610000000000.0,29640000000000.0,.,30.0,29610.0,08:13:30,06:13:30,29640.0,08:14:00,06:14:00

Counting the total number of annotations:

In [12]:
# table( d$ANNOT )
tbl.ANNOT.value_counts().sort_index()

ANNOT
Arousal    1232
N1         1317
N2         7444
N3         1805
R          1942
W          2935
Name: count, dtype: int64

We can extract the counts stratified by individual:

In [13]:
# table( d$ID, d$ANNOT )
import pandas as pd
pd.crosstab( tbl.ID , tbl.ANNOT )

ANNOT  Arousal   N1   N2   N3    R    W
ID
F01         86   55  361  148  118  161
F02         97   36  431  145  180   69
F03          0   41   40   15    6   36
F04          0   36   65   18   19   45
F05        105   78  380  141  114  183
F06          0   24   36   18   18   21
F07         83   25  426   42  141  310
F08        159  108  366  103  132  134
F09         81   44  477   63  147   48
F10        131   81  426   84  147  183
M01        132  102  592   61   42   79
M02         41   30  304   11   17   97
M03          0   82  434  120  180  122
M04          0   99  344  160  103  245
M05          0   84  593   83   75   98
M06          0   71  435   63  132  212
M07          0   40  434   97   64  363
M08          0   64  421   96   71  330
M09         91   45  472  257  122   81
M10        226  172  407   80  114  118

Finally, we can look at the average duration of each annotation class:

In [16]:
# round( tapply( d$DUR , list( d$ID , d$ANNOT ) , mean ) ,2 ) 
tbl.groupby( [ 'ID', 'ANNOT' ] )[ 'DUR' ].mean().unstack().reset_index()

ANNOT,ID,Arousal,N1,N2,N3,R,W
0,F01,11.030233,30.0,30.0,30.0,30.0,30.0
1,F02,11.305155,30.0,30.0,30.0,30.0,30.0
2,F03,NaN,56.341463,168.0,344.0,510.0,251.666667
3,F04,NaN,42.5,174.461538,281.666667,217.894737,89.333333
4,F05,13.028571,30.0,30.0,30.0,30.0,30.0
5,F06,NaN,56.25,371.666667,225.0,253.333333,55.714286
6,F07,12.742169,30.0,30.0,30.0,30.0,30.0
7,F08,11.715723,30.0,30.0,30.0,30.0,30.0
8,F09,12.385185,30.0,30.0,30.0,30.0,30.0
9,F10,11.1,30.0,30.0,30.0,30.0,30.0
10,M01,11.621212,30.0,30.0,30.0,30.0,30.0
11,M02,12.336585,30.0,30.0,30.0,30.0,30.0
12,M03,NaN,30.0,30.0,30.0,30.0,30.0
13,M04,NaN,30.0,30.0,30.0,30.0,30.0
14,M05,NaN,30.0,30.0,30.0,30.0,30.0
15,M06,NaN,30.0,30.0,30.0,30.0,30.0
16,M07,NaN,30.0,30.0,30.0,30.0,30.0
17,M08,NaN,30.0,30.0,30.0,30.0,30.0
18,M09,13.741758,30.0,30.0,30.0,30.0,30.0
19,M10,12.087168,30.0,30.0,30.0,30.0,30.0

See the main walkthrough pages for commentary on these values.

---

This concludes this section (as noted in the original walkthrough, you can use `scope()` to view the annotations).

After doing that, we can move on to the [next section](02_hypno.ipynb) making hypnogram-based plots and statistics.